// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static struct speed s_speed = {100, 500,
                               1000};  // Default speeds for LEDs in ms
void glue_get_speed(struct speed *data) {
    *data = s_speed;  // Sync with your device
}
void glue_set_speed(struct speed *data) {
    s_speed = *data;  // Sync with your device
}
